feat(portal): add env variables for port
mycloudnexus/vortex pull request #117
Opened 2024-12-24 08:03 UTC by yangpangpangya

## Description
add env variables for port 
update login page , should have loading style when user have login

## Related Issue

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] CI/CD or documentation update (changes to CI/CD pipeline or documentation)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

2024-12-26 04:38 UTC, pccw-josorio approved these changes

2024-12-27 00:21 UTC, pori requested changes

2024-12-27 00:21 UTC, pori commented on vortex-app/vortex-app-portal/src/components/Layout/NavMain.tsx
> +const withoutLogo = ENV.COMPANY_LOGO_URL?.includes('RUNTIME') || !ENV.COMPANY_LOGO_URL
Why not just keep the default values empty?

2024-12-27 00:21 UTC, pori commented on vortex-app/vortex-app-portal/.env
> +AUTH0_MGMT_ORG_ID=65a4f18aec61ae42ae9606df
Since this project is open source, you should not be adding configuration for a real Auth0 application otherwise it could be taken advantage of by malicious users.

Given this is now exposed to the public via this PR, I would suggest retiring the application and creating a new one.

2024-12-27 00:21 UTC, pori commented on vortex-app/vortex-app-portal/.env
> +CUSTOMER_AUTH0_CLIENT_ID=kzs6w6eeEx0uy9FOFeEXybRKwUyQzEXB
As above.

2024-12-27 00:21 UTC, pori commented on vortex-app/vortex-app-portal/.env
> +PRICING_PAYDOLLAR_MERCHANT_ID="88142043"
As above.

2024-12-27 00:21 UTC, pori commented on vortex-app/vortex-app-portal/.env.production
> +NETWORK_UTILISATION_ENABLE=RUNTIME_NETWORK_UTILISATION_ENABLE
I see this is the pattern we're already follow but it makes more sense to just keep them empty.

2024-12-27 00:21 UTC, pori commented on vortex-app/vortex-app-portal/src/components/Layout/SettingsMenu.tsx
> +          navigate('/')
Is this a force refresh? What is keeping this from happening indefinitely?

2024-12-27 00:21 UTC, pori commented on vortex-app/vortex-app-portal/src/pages/Login/index.tsx
> +  const searchParams = new URLSearchParams(search?.slice(1))
nitpick: set `search?.slice(1)` to a constant so we know what the expected value should be.

2024-12-27 01:39 UTC, yangpangpangya commented on vortex-app/vortex-app-portal/src/components/Layout/NavMain.tsx
> +const withoutLogo = ENV.COMPANY_LOGO_URL?.includes('RUNTIME') || !ENV.COMPANY_LOGO_URL
because  base on product needs. If the user does not have their own logo, our product logo will be displayed by default.

2024-12-27 01:42 UTC, yangpangpangya commented on vortex-app/vortex-app-portal/.env
> +AUTH0_MGMT_ORG_ID=65a4f18aec61ae42ae9606df
sorry for that, i have remove it

2024-12-27 01:42 UTC, yangpangpangya commented on vortex-app/vortex-app-portal/.env
> +PRICING_PAYDOLLAR_MERCHANT_ID="88142043"
remove

2024-12-27 01:42 UTC, yangpangpangya commented on vortex-app/vortex-app-portal/.env
> +CUSTOMER_AUTH0_CLIENT_ID=kzs6w6eeEx0uy9FOFeEXybRKwUyQzEXB
remove

2024-12-27 01:43 UTC, yangpangpangya commented on vortex-app/vortex-app-portal/src/components/Layout/SettingsMenu.tsx
> +          navigate('/')
this is a feature, if a reseller user switch to a customer company, we will go to the dashboard

2024-12-27 02:03 UTC, yangpangpangya commented on vortex-app/vortex-app-portal/.env.production
> +NETWORK_UTILISATION_ENABLE=RUNTIME_NETWORK_UTILISATION_ENABLE
this is the rule for our production environment variable replacement, I just follow it

2024-12-27 02:18 UTC, yangpangpangya commented on vortex-app/vortex-app-portal/src/pages/Login/index.tsx
> +  const searchParams = new URLSearchParams(search?.slice(1))
do you mean the default value? it will get query parameters from url ,the value of `search?.slice(1)`should like this `query1=value1&query2=value2`

2024-12-30 04:41 UTC, pori approved these changes

2024-12-30 23:14 UTC, DaveXiong approved these changes

2024-12-30 23:16 UTC, merged