feat(sdk): support saml connection
mycloudnexus/vortex pull request #30
Opened 2024-10-29 10:18 UTC by jackworkgit

2024-10-29 11:35 UTC, DaveXiong requested changes
comments added

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +    if (request.getStrategy().equals(ConnectionStrategryEnum.SAML)) {
move if ... else .. to OrganizationService.createConnection(...)

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +            service.updateSAML(
The update code looks only support SAML, but creationg support OIDC , DB and SAML

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/CreateConnectionDto.java
> +  private SamlConnection samlConnection;
rename `samlConnection` to `saml`

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/SamlConnection.java
> +  private ConnectionOptions options;
Looks like you can move all properties from COnnectionOptions to SamlConnection class, and delete ConnectionOptions

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/UpdateConnectionDto.java
> +  private SamlConnection samlConnection;
rename `samlConnection` to `saml`

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/enums/ConnectionStrategryEnum.java
> +  DB("auth0");
maybe rename `DB` to `AUTH0` ?  a bit confuse mapping DB to auth0.

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/model/AttributeProperty.java
> +public class AttributeProperty {
What's the purpose of this class ? from the name , not sure what's the purpose of this class.

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/ConnectionService.java
> +      ManagementAPI managementAPI,
looks like you want to delete the following data from this org:
1. all members
2. all pending invitations
3. all  connections

Pls check if the function only accept the parameter `orgId` should be ok.

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +      findOrganization(orgId, organizationsEntity);
Pls check why the return of  `findOrganization` won't be assigned to only varirable

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +      if (organization.getMetadata().get(META_STATUS).equals(OrgStatusEnum.ACTIVE.name())
looks like you missed the logic:
metadata.status == INACTIVE && request.status == ACTIVE

2024-10-29 11:35 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +  public OrganizationConnection dbConnection(String orgId, String requestedBy) {
rename to `createDBConnection`

2024-10-29 11:36 UTC, DaveXiong commented
And pls fix the issues reported by SonarCloud

2024-10-30 00:38 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/enums/ConnectionStrategryEnum.java
> +  DB("auth0");
OK

2024-10-30 00:39 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +    if (request.getStrategy().equals(ConnectionStrategryEnum.SAML)) {
ok

2024-10-30 00:45 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/model/AttributeProperty.java
> +public class AttributeProperty {
To wrap Auth0 attributes. Or just use Map<String, Object>, there are a few fields.

2024-10-30 00:47 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/ConnectionService.java
> +      ManagementAPI managementAPI,
Only one `orgId` may have issues. Old connections should be passed in this method.

2024-10-30 00:53 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +      if (organization.getMetadata().get(META_STATUS).equals(OrgStatusEnum.ACTIVE.name())
The code is formatted to a new line. My logic is above.

2024-10-30 00:59 UTC, ahasgx commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +      findOrganization(orgId, organizationsEntity);
1. Check organization exists before updating an organization，
2. updating an organization cannot use the variable organization  which queries from auth0, so  not assigned to variable

2024-10-30 00:59 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +      if (organization.getMetadata().get(META_STATUS).equals(OrgStatusEnum.ACTIVE.name())
Here, the connection needs to be deleted to change the state from ACTIVE to INACTIVE.

2024-10-30 01:35 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +            service.updateSAML(
Now I think we can only oidc/saml updating. DB is created with no more parameters.

2024-10-30 03:16 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +    if (request.getStrategy().equals(ConnectionStrategryEnum.SAML)) {
better to add more logic there:

```
if (request.getStrategy() == ConnectionStrategryEnum.SAML) {
      return createSAMLConnection(orgId, request.getSaml());
    } else if (request.getStrategy() == ConnectionStrategryEnum.OIDC) {
      return createOidcConnection(orgId, request);
    } else {
      throw VortexException.badRequest("Invalid connection strategy");
    }
```

2024-10-30 03:16 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +          JsonToolkit.createObjectMapper().convertValue(samlConnection.getOptions(), Map.class);
Pls check the following code inspection description:
```
Unchecked assignment: 'java. util. Map' to 'java. util. Map<java. lang. String,java. lang. Object>' 
```

2024-10-30 03:16 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +          JsonToolkit.createObjectMapper().convertValue(samlConnection.getOptions(), Map.class);
Pls check the following code inspection description:

Unchecked assignment: 'java. util. Map' to 'java. util. Map<java. lang. String,java. lang. Object>'

2024-10-30 03:34 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/ConnectionService.java
> +      ManagementAPI managementAPI,
the above business logic will delete all members and invitations inside the organization, but only delete the specific connection, Does it make sense?  Looks like you would like to delete all data inside the organization ?

2024-10-30 03:36 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +    return updateSAMLConnection(orgId, request.getId(), request.getSaml());
Pls add the logic as following
```
if (request.getStrategy() == ConnectionStrategryEnum.SAML) {
      
    } else if (request.getStrategy() == ConnectionStrategryEnum.OIDC) {
      
    } else {
      throw VortexException.badRequest("Invalid connection strategy");
    }
```

2024-10-30 13:01 UTC, DaveXiong approved these changes
LGTM

2024-10-30 13:02 UTC, merged