gateway filter and create port order
mycloudnexus/vortex pull request #33
Opened 2024-10-31 03:08 UTC by ahasgx

1. gateway filter config
2. define response body process adapter (automatic register adapter by route-adapter configuration)
3. global filter to process response with adapters
4. create port order for vortex

2024-10-31 05:43 UTC, DaveXiong commented on vortex-app/vortex-app-api/src/main/resources/application.yaml
> +      route-path: /consoleconnect/api/company/consolecore-poping-company/ports/orders
pls make sure `consolecore-poping-company` can be configured

2024-10-31 05:43 UTC, DaveXiong commented on vortex-app/vortex-app-api/src/main/resources/application.yaml
> +    consoleconnect:
looks like `gateway.consoleconnect` can be deleted, use `gateway.downstream` should be OK.

2024-10-31 05:51 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/filter/ResponseAdapterGlobalFilter.java
> +public class ResponseAdapterGlobalFilter implements GlobalFilter, Ordered {
This is a global filter, looks like it will apply to all endpoints, Pls check if it's possible to convert it to AbstractGatewayFilterFactory, then you should be able to config it based on spring cloud gateway confgiuration.
Pls ref https://github.com/mycloudnexus/vortex/tree/main/vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/filter
and config https://github.com/mycloudnexus/vortex/blob/main/vortex-app/vortex-app-api/src/main/resources/application.yaml#L60

2024-10-31 06:08 UTC, ahasgx commented on vortex-app/vortex-app-api/src/main/resources/application.yaml
> +    consoleconnect:
We will configure multiple routers(consoleconnect, sonata...), so I think we need to specify route names.

2024-10-31 06:09 UTC, ahasgx commented on vortex-app/vortex-app-api/src/main/resources/application.yaml
> +      route-path: /consoleconnect/api/company/consolecore-poping-company/ports/orders
ok

2024-10-31 06:30 UTC, ahasgx commented on vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/filter/ResponseAdapterGlobalFilter.java
> +public class ResponseAdapterGlobalFilter implements GlobalFilter, Ordered {
ResponseAdapterGatewayFilterFactory

2024-10-31 07:24 UTC, pori requested changes
The gateway filtering code looks okay. Granted, I do have some questions.

There might be problems with port ordering. 

Could we split these up into two PRs? It would would make these quicker to review.

2024-10-31 07:24 UTC, pori commented on vortex-app/vortex-app-api/src/main/resources/application.yaml
> +                userKey: Bearer ${app.gateway.consoleconnect.user-api-key}
Wouldn't we just have one api key representing the reseller?

2024-10-31 07:24 UTC, pori commented on vortex-app/vortex-app-api/src/main/resources/application.yaml
> +      base-url: ${GATEWAY_DOWN_STREAM_BASE_URL:https://api.test.consoleconnect.com}
```suggestion
      base-url: ${GATEWAY_DOWN_STREAM_BASE_URL:https://api.consoleconnect.com}
```

Given this is an open source project, I would prefer to have public urls only.

2024-10-31 07:24 UTC, pori commented on vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/adapter/cc/PortOrderCreateAdapter.java
> +    String resourceId = JsonPathToolkit.read(response, "$.createdPortId");
This field is always `null` upon port ordering. You will have to poll for the value via get by id route.

2024-10-31 07:34 UTC, ahasgx commented on vortex-app/vortex-app-api/src/main/resources/application.yaml
> +                userKey: Bearer ${app.gateway.consoleconnect.user-api-key}
two keys are different authority tokens of consoleconnection API for access,  adminKey can create resource(port order...), and userKey just can read-only data

2024-10-31 07:38 UTC, ahasgx commented on vortex-app/vortex-app-api/src/main/resources/application.yaml
> +      base-url: ${GATEWAY_DOWN_STREAM_BASE_URL:https://api.test.consoleconnect.com}
we can config base-url in different env ,

2024-10-31 07:44 UTC, ahasgx commented on vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/adapter/cc/PortOrderCreateAdapter.java
> +    String resourceId = JsonPathToolkit.read(response, "$.createdPortId");
yeah, createdPortId is null when creating a new port order, here just try to read createdPortId. createdPortId will sync to order table of vortex when request list port orders

2024-10-31 07:49 UTC, ahasgx commented on vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/adapter/cc/PortOrderCreateAdapter.java
> +    String resourceId = JsonPathToolkit.read(response, "$.createdPortId");
This field is always null, i will delete it later, thanks

2024-11-01 04:58 UTC, pori approved these changes

2024-11-01 05:01 UTC, DaveXiong approved these changes
LGTM

2024-11-01 05:01 UTC, merged