feat(sdk): customer user's operations
mycloudnexus/vortex pull request #67
Opened 2024-11-18 07:48 UTC by jackworkgit

1. Reset the password for a customer user or let the user complete the reset password flow.
2. Resent an invitation email to a user and let them register.
3. Disable a user from the existing list.
4. Delete a user from the existing list.

2024-11-19 06:40 UTC, DaveXiong requested changes
comments added

2024-11-19 06:40 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @DeleteMapping("/{orgId}/invitations/revoke/{invitationId}")
This is to delete a existing invitation, I prefer you can change the endpoint to 
```
DELETE   /{orgId}/invitations/{invitationId}
```

2024-11-19 06:40 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PatchMapping("/{orgId}/user/{userId}/block")
the endpoint mean `block` the user, better to rename it to avoid the confusing.

2024-11-19 06:40 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PutMapping("/{orgId}/invitations/re-invitation/{invitationId}")
I am not sure if we need to support a function `re-invitation`, seems `re-inviation` can be done via

1. delete a existing invitation
2. create a invitation again

2024-11-19 06:40 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  public Mono<HttpResponse<Void>> reset(
rename `reset` to `resetPassword`

2024-11-19 06:40 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/UserController.java
> +  public Mono<HttpResponse<Void>> reset(
rename `reset` to `resetPassword`

2024-11-19 06:40 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +  public Void reset(String orgId, String userId, String requestedBy) {
rename `reset` to `resetPassword`

2024-11-19 06:41 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PutMapping("/{orgId}/invitations/re-invitation/{invitationId}")
The inner logic of Auth0 will delete the old one and create a new invitation record.

2024-11-19 06:42 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/UserController.java
> +  @PostMapping("/{orgId}/reset-password")
move this function to UserOrganizationController.java
the endpoint can be 
```
POST /reset-password
```

2024-11-19 06:43 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @DeleteMapping("/{orgId}/invitations/revoke/{invitationId}")
Ok

2024-11-19 06:46 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/UserController.java
> +  @PostMapping("/{orgId}/reset-password")
ok

2024-11-19 06:51 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PatchMapping("/{orgId}/user/{userId}/block")
Let me change the method name.

2024-11-19 06:57 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  public Mono<HttpResponse<Void>> reset(
ok

2024-11-19 07:33 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +  public Void reset(String orgId, String userId, String requestedBy) {
renamed

2024-11-19 23:02 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PutMapping("/{orgId}/invitations/re-invitation/{invitationId}")
Yes, FE can delete it first and then create it again. but it depends on the `create` implementation in BE.
BE can delete it first and then create it in the `create` implemenattion.

2024-11-19 23:51 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/auth0/Auth0Client.java
> +    return AuthAPI.newBuilder(
Pls take note there is already a AuthAPI created
https://github.com/mycloudnexus/vortex/blob/main/vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/auth0/Auth0Client.java#L26

```
    this.auth0AuthAPI =
        AuthAPI.newBuilder(
                this.auth0Property.getMgmtApi().getDomain(),
                this.auth0Property.getMgmtApi().getClientId(),
                this.auth0Property.getMgmtApi().getClientSecret())
            .withHttpClient(auth0HttpClient)
            .build();
```

Pls double check if it's need to build a new one.

2024-11-20 00:53 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/auth0/Auth0Client.java
> +    return AuthAPI.newBuilder(
Later I will delete this old created `AuthAPI` , it can't work well.
![image](https://github.com/user-attachments/assets/6f9c3ac9-db27-4731-8d30-c0052a9d36a2)

2024-11-20 01:11 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PutMapping("/{orgId}/invitations/re-invitation/{invitationId}")
After discussing with FE, I will delete it.

2024-11-20 01:17 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PutMapping("/{orgId}/invitations/re-invitation/{invitationId}")
BE doesn't need to delete the old one and can call the `create` endpoint duplicate.

2024-11-20 01:55 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PutMapping("/{orgId}/invitations/re-invitation/{invitationId}")
This endpoint has been deleted.

2024-11-20 02:42 UTC, DaveXiong reviewed
comment added

2024-11-20 02:42 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PostMapping("/{orgId}/reset-password/{userId}")
rename it to `/{orgId}/members/{memberId}/reset-password`

2024-11-20 02:42 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PatchMapping("/{orgId}/user/{userId}/change-status")
rename it to `/{orgId}/members/{memberId}/change-status`

2024-11-20 02:42 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +      return this.auth0Client
looks like you need to check if the connection support reset-password  ?

2024-11-20 02:42 UTC, DaveXiong commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +  private Member checkAndGetMember(
I prefer you can rename it to `findMemberById( ...)

2024-11-20 02:53 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +      return this.auth0Client
Added. Auth0 will also check that.

2024-11-20 02:53 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
> +  @PostMapping("/{orgId}/reset-password/{userId}")
renamed

2024-11-20 02:53 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
> +  private Member checkAndGetMember(
renamed

2024-11-20 03:16 UTC, DaveXiong approved these changes

2024-11-20 05:26 UTC, pori approved these changes

2024-11-20 05:29 UTC, merged