feat(sdk): change the member list logic
mycloudnexus/vortex pull request #82
Opened 2024-11-26 05:44 UTC by jackworkgit

List users from auth0 by organization's members.

2024-11-26 06:03 UTC, DylanMeissner requested changes

2024-11-26 06:03 UTC, DylanMeissner commented on vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/service/OrganizationServiceTest.java
> -  void test_listMembers() {
Why are you removing this test, shouldn't you be updating it to accomodate for the new functionality added?

2024-11-26 06:10 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/service/OrganizationServiceTest.java
> -  void test_listMembers() {
Here is the new testing method and the new function can be covered.  `com.consoleconnect.vortex.iam.controller.OrganizationControllerTest#givenOrganizationInitialized_whenRetrieveMembers_thenReturn200 ` . As you can see the coverage is 81.2%.

2024-11-26 06:48 UTC, jackworkgit commented on vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/service/OrganizationServiceTest.java
> -  void test_listMembers() {
Now this method is duplicated.

2024-11-26 23:09 UTC, DylanMeissner approved these changes

2024-11-27 02:23 UTC, katykk193 approved these changes

2024-11-27 02:51 UTC, merged